(import (scheme process-context))

(define families
  '(("code_analyzer" "classic-six.code_analyzer" "classic-six" "analysisFocus" "syntax-form-audit")
    ("data_processing" "classic-six.data_processing" "classic-six" "dataWindow" "list-stream-reconciliation")
    ("jargon" "classic-six.jargon" "classic-six" "languagePolicy" "scheme-r7rs-glossary")
    ("metrics" "classic-six.metrics" "classic-six" "signalBlend" "latency-error-tail-call")
    ("network_activity" "classic-six.network_activity" "classic-six" "transportMix" "socket-http-sse")
    ("system_monitoring" "classic-six.system_monitoring" "classic-six" "telemetryScope" "chibi-runtime-host")
    ("agent_workflows" "modern-core.agent_workflows" "modern-core" "coordinationMode" "continuation-dispatch-handshake")
    ("platform_engineering" "modern-core.platform_engineering" "modern-core" "platformSurface" "chibi-native-validation-lane")
    ("observability_ai_runtime" "modern-core.observability_ai_runtime" "modern-core" "runtimeSignals" "logs-metrics-provider-boundary")
    ("delivery_preview_ops" "modern-core.delivery_preview_ops" "modern-core" "deliveryGuardrail" "script-preview-checkpoints")
    ("supply_chain_security" "modern-core.supply_chain_security" "modern-core" "supplyChainPosture" "source-script-attestation")
    ("ai_inference_ops" "fallback.ai_governance" "fallback-ai_governance" "fallbackFamily" "ai_governance")
    ("evaluation_and_guardrails" "fallback.ai_governance" "fallback-ai_governance" "fallbackFamily" "ai_governance")
    ("knowledge_retrieval" "fallback.ai_governance" "fallback-ai_governance" "fallbackFamily" "ai_governance")
    ("edge_client_runtime" "fallback.ai_governance" "fallback-ai_governance" "fallbackFamily" "ai_governance")
    ("identity_and_trust" "fallback.ai_governance" "fallback-ai_governance" "fallbackFamily" "ai_governance")
    ("aibom_provenance" "fallback.ai_governance" "fallback-ai_governance" "fallbackFamily" "ai_governance")
    ("agent_boundary_security" "fallback.ai_governance" "fallback-ai_governance" "fallbackFamily" "ai_governance")
    ("embedded_agentic_pipeline" "fallback.ai_governance" "fallback-ai_governance" "fallbackFamily" "ai_governance")
    ("data_governance_compliance" "fallback.ai_governance" "fallback-ai_governance" "fallbackFamily" "ai_governance")
    ("finops_capacity" "fallback.ai_governance" "fallback-ai_governance" "fallbackFamily" "ai_governance")
    ("blockchain_protocol_ops" "fallback.security_blockchain" "fallback-security_blockchain" "fallbackFamily" "security_blockchain")
    ("cross_chain_interop" "fallback.security_blockchain" "fallback-security_blockchain" "fallbackFamily" "security_blockchain")
    ("proof_and_sequencer_ops" "fallback.security_blockchain" "fallback-security_blockchain" "fallbackFamily" "security_blockchain")
    ("hybrid_runtime_ops" "fallback.overlay_quantum" "fallback-overlay_quantum" "fallbackFamily" "overlay_quantum")
    ("capacity_cost_controller" "fallback.overlay_quantum" "fallback-overlay_quantum" "fallbackFamily" "overlay_quantum")
    ("batch_execution_tuner" "fallback.overlay_quantum" "fallback-overlay_quantum" "fallbackFamily" "overlay_quantum")
    ("compiler_maintainer" "fallback.overlay_quantum" "fallback-overlay_quantum" "fallbackFamily" "overlay_quantum")
    ("interop_adapter_engineer" "fallback.overlay_quantum" "fallback-overlay_quantum" "fallbackFamily" "overlay_quantum")
    ("preflight_capacity_planner" "fallback.overlay_quantum" "fallback-overlay_quantum" "fallbackFamily" "overlay_quantum")
    ("simulator_performance_engineer" "fallback.overlay_quantum" "fallback-overlay_quantum" "fallbackFamily" "overlay_quantum")
    ("fhir_profile_generator" "fallback.health_protocol" "fallback-health_protocol" "fallbackFamily" "health_protocol")
    ("smart_launch_oauth" "fallback.health_protocol" "fallback-health_protocol" "fallbackFamily" "health_protocol")
    ("bulk_fhir_population_ops" "fallback.health_protocol" "fallback-health_protocol" "fallbackFamily" "health_protocol")
    ("hl7v2_feed_ops" "fallback.health_protocol" "fallback-health_protocol" "fallbackFamily" "health_protocol")
    ("clinical_workflow_events" "fallback.health_protocol" "fallback-health_protocol" "fallbackFamily" "health_protocol")
    ("dicomweb_imaging_ops" "fallback.health_protocol" "fallback-health_protocol" "fallbackFamily" "health_protocol")
    ("openehr_semantic_record_ops" "fallback.health_protocol" "fallback-health_protocol" "fallbackFamily" "health_protocol")
    ("device_telemetry_clinical" "fallback.health_protocol" "fallback-health_protocol" "fallbackFamily" "health_protocol")
    ("emr_vendor_adapter" "fallback.health_protocol" "fallback-health_protocol" "fallbackFamily" "health_protocol")
    ("ocpp_chargepoint_ops" "fallback.health_protocol" "fallback-health_protocol" "fallbackFamily" "health_protocol")
    ("ocpi_roaming_ops" "fallback.health_protocol" "fallback-health_protocol" "fallbackFamily" "health_protocol")
    ("mcp_a2a_ops" "fallback.health_protocol" "fallback-health_protocol" "fallbackFamily" "health_protocol")
    ("streaming_bus_ops" "fallback.health_protocol" "fallback-health_protocol" "fallbackFamily" "health_protocol")
    ("service_mesh_rpc_ops" "fallback.health_protocol" "fallback-health_protocol" "fallbackFamily" "health_protocol")))

(define (string-map-char proc value)
  (list->string (map proc (string->list value))))

(define (registry-id value)
  (string-map-char (lambda (ch) (if (char=? ch #\_) #\- ch)) value))

(define (normalize-family value)
  (string-map-char (lambda (ch) (if (char=? ch #\-) #\_ (char-downcase ch))) value))

(define (find-family value)
  (let ((normalized (normalize-family value)))
    (let loop ((items families))
      (cond ((null? items) #f)
            ((string=? (car (car items)) normalized) (car items))
            (else (loop (cdr items)))))))

(define (fnv1a value)
  (let loop ((chars (string->list value)) (hash 2166136261))
    (if (null? chars)
        hash
        (loop (cdr chars) (modulo (+ (* hash 16777619) (char->integer (car chars))) 4294967296)))))

(define (pad2 value)
  (let ((text (number->string value)))
    (if (< value 10) (string-append "0" text) text)))

(define (line label value)
  (display label)
  (display value)
  (newline))

(define (join-quoted items)
  (let loop ((xs items) (first? #t))
    (cond ((null? xs) "")
          (else (string-append (if first? "" ",") "\"" (car xs) "\"" (loop (cdr xs) #f))))))

(define (registry-slice start end)
  (let loop ((items families) (index 0) (out '()))
    (cond ((null? items) (reverse out))
          ((and (>= index start) (< index end))
           (loop (cdr items) (+ index 1) (cons (registry-id (car (car items))) out)))
          (else (loop (cdr items) (+ index 1) out)))))

(define (print-registry)
  (display "{\"outputFormats\":[\"text\",\"json\"],")
  (display "\"flags\":[\"list-values\",\"focus-family\",\"output-format\",\"seed\",\"experimental-provider\"],")
  (display "\"generatorFamilies\":[")
  (let loop ((items families) (first? #t))
    (if (not (null? items))
        (let ((f (car items)))
          (display (if first? "" ","))
          (display "{\"id\":\"") (display (list-ref f 0))
          (display "\",\"registryId\":\"") (display (registry-id (list-ref f 0)))
          (display "\",\"rendererKey\":\"") (display (list-ref f 1))
          (display "\",\"tranche\":\"") (display (list-ref f 2))
          (display "\"}")
          (loop (cdr items) #f))))
  (display "],\"classicSix\":[") (display (join-quoted (registry-slice 0 6)))
  (display "],\"modernCore\":[") (display (join-quoted (registry-slice 6 11)))
  (display "],\"fallbackFamilies\":[") (display (join-quoted (registry-slice 11 (length families))))
  (display "],\"implementationMode\":\"family-focus-deterministic\"}\n"))

(define (print-payload family seed output-format)
  (let* ((id (list-ref family 0))
         (renderer (list-ref family 1))
         (tranche (list-ref family 2))
         (context-key (list-ref family 3))
         (context-value (list-ref family 4))
         (registry (registry-id id))
         (hash (fnv1a (string-append seed "::" id)))
         (seconds (modulo hash 86400))
         (hour (quotient seconds 3600))
         (minute (quotient (modulo seconds 3600) 60))
         (second (modulo seconds 60))
         (sequence (+ 1000 (modulo hash 9000)))
         (timestamp (string-append "2026-01-01T" (pad2 hour) ":" (pad2 minute) ":" (pad2 second) "Z")))
    (if (string=? output-format "json")
        (begin
          (display "{\"eventType\":\"stakeholder.generator.output\",\"sequence\":") (display sequence)
          (display ",\"family\":\"") (display id)
          (display "\",\"message\":\"Deterministic scheme tranche for ") (display id)
          (display "\",\"timestamp\":\"") (display timestamp)
          (display "\",\"context\":{\"rendererKey\":\"") (display renderer)
          (display "\",\"") (display context-key) (display "\":\"") (display context-value)
          (display "\",\"seedFingerprint\":\"") (display registry) (display "-") (display (number->string hash 16))
          (display "\",\"tranche\":\"") (display tranche)
          (display "\",\"schemeProfile\":\"chibi-r7rs-list-catalog\"},")
          (display "\"generationProvenance\":{\"sourceRepo\":\"scheme-stakeholder\",\"baseline\":\"local-small-tranche-family-focus\",\"experimental\":false,\"adapterType\":\"static-list-catalog\",\"promptVersion\":null},\"outputFormat\":\"json\"}\n"))
        (begin
          (line "family: " id)
          (line "renderer: " renderer)
          (line "tranche: " tranche)
          (line "sequence: " sequence)
          (line "timestamp: " timestamp)
          (line "message: Deterministic scheme tranche for " id)))))

(define (fail message . value)
  (display message (current-error-port))
  (if (not (null? value))
      (begin (display ": " (current-error-port)) (display (car value) (current-error-port))))
  (newline (current-error-port))
  (exit 2))

(define (main args)
  (let loop ((args args) (focus-family #f) (seed "default-seed") (output-format "text") (list-values #f))
    (cond
      ((null? args)
       (cond (list-values (print-registry))
             ((not focus-family) (fail "focus-family is required and must be a known generator family"))
             (else (let ((family (find-family focus-family)))
                     (if family (print-payload family seed output-format) (fail "invalid --focus-family" focus-family))))))
      ((string=? (car args) "--list-values") (loop (cdr args) focus-family seed output-format #t))
      ((string=? (car args) "--focus-family") (if (null? (cdr args)) (fail "missing value for --focus-family") (loop (cddr args) (cadr args) seed output-format list-values)))
      ((string=? (car args) "--seed") (if (null? (cdr args)) (fail "missing value for --seed") (loop (cddr args) focus-family (cadr args) output-format list-values)))
      ((string=? (car args) "--output-format")
       (if (null? (cdr args))
           (fail "missing value for --output-format")
           (if (or (string=? (cadr args) "text") (string=? (cadr args) "json"))
               (loop (cddr args) focus-family seed (cadr args) list-values)
               (fail "invalid --output-format" (cadr args)))))
      ((string=? (car args) "--experimental-provider")
       (if (null? (cdr args)) (fail "missing value for --experimental-provider") (fail "experimental provider is not enabled in the deterministic first tranche" (cadr args))))
      ((and (>= (string-length (car args)) 15) (string=? (substring (car args) 0 15) "--experimental-")) (fail "experimental flags require --experimental-provider"))
      (else (fail "unknown argument" (car args))))))

(main (cdr (command-line)))
